# Netflix Shows Data ETL on GCP
This notebook is working on a ETL pipeline design for netflix shows and movies data from Kaggle, enriching the data from the open source API in OMDb.

*Source*: [Netflix TV Shows and Movies](https://www.kaggle.com/datasets/victorsoeiro/netflix-tv-shows-and-movies)

### 1. Import Necessary Libraries

In [1]:
import requests
import json
import os
import pandas as pd

import time

### 2. Read the CSV File and Import the Data as a Pandas Dataframe

In [2]:
df_titles = pd.read_csv('/home/jasonzelin/data-analytics-portfolio/[in_progress]_netflix_data_etl_on_gcp/data/titles.csv')
df_credits = pd.read_csv('/home/jasonzelin/data-analytics-portfolio/[in_progress]_netflix_data_etl_on_gcp/data/credits.csv')

In [3]:
print('Titles:\n') 
print(df_titles.info(), '\n')
print('Credits:\n') 
print(df_credits.info())

Titles:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5850 entries, 0 to 5849
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    5850 non-null   object
 1   title                 5849 non-null   object
 2   type                  5850 non-null   object
 3   description           5832 non-null   object
 4   release_year          5850 non-null   int64
 5   age_certification     3231 non-null   object
 6   runtime               5850 non-null   int64
 7   genres                5850 non-null   object
 8   production_countries  5850 non-null   object
 9   seasons               2106 non-null   float64
 10  imdb_id               5447 non-null   object
 11  imdb_score            5368 non-null   float64
 12  imdb_votes            5352 non-null   float64
 13  tmdb_popularity       5759 non-null   float64
 14  tmdb_score            5539 non-null   float64
dtypes: float64(5), int64(2), object(8)
memory usage: 685.7+ KB
None

Credits:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77801 entries, 0 to 77800
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   person_id  77801 non-null  int64
 1   id         77801 non-null  object
 2   name       77801 non-null  object
 3   character  68029 non-null  object
 4   role       77801 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.0+ MB
None

### 3. Enriching the data from Kaggle Dataset with OMDb API Data

In [4]:
my_api_key = 'fd7f3858'
base_url = 'http://www.omdbapi.com/'
title = ''

params = {
    'apikey': my_api_key,
    't': title
}

In [ ]:
titles_list = missing_titles
omdb_data = []

for i in titles_list:
    params['t'] = i
    response = requests.get(base_url, params=params)
    data = response.json()
    if data.get("Error") == "Request limit reached!":
        print("⚠️ API daily limit reached. Breaking loop.")
        break
    omdb_data.append(data)
    time.sleep(0.2)  # To respect API rate limits

for i, v in enumerate(omdb_data):
    omdb_data[i]['original_title'] = titles_list[i]

⚠️ API daily limit reached. Breaking loop.

In [44]:
omdb_data

[{'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Five Came Back: The Reference Films'},
 {'Title': "Monty Python's Life of Brian",
  'Year': '1979',
  'Rated': 'R',
  'Released': '17 Aug 1979',
  'Runtime': '94 min',
  'Genre': 'Comedy',
  'Director': 'Terry Jones',
  'Writer': 'Graham Chapman, John Cleese, Terry Gilliam',
  'Actors': 'Graham Chapman, John Cleese, Michael Palin',
  'Plot': 'Born on the original Christmas in the stable next door to Jesus Christ, Brian of Nazareth spends his life being mistaken for a messiah.',
  'Language': 'English, Latin',
  'Country': 'United Kingdom',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNDMzY2E4NjEtMTJiZC00Y2UzLWFiM2MtZWVhNTg5OGQxNjk1XkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.0/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '96%'},
   {'Source': 'Metacritic', 'Value': '77/100'}],
  'Metascore': '77',
  'imdbRating': '8.0',
  'imdbVotes': '430,381',
  'imdbID': 'tt0079470',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$20,206,622',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Life of Brian'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Alexandria… Why?'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Saladin the Victorious'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Beirut, Oh Beirut'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'The Return of the Prodigal Son'},
 {'Title': 'Goodfellas',
  'Year': '1990',
  'Rated': 'R',
  'Released': '21 Sep 1990',
  'Runtime': '145 min',
  'Genre': 'Biography, Crime, Drama',
  'Director': 'Martin Scorsese',
  'Writer': 'Nicholas Pileggi, Martin Scorsese',
  'Actors': 'Robert De Niro, Ray Liotta, Joe Pesci',
  'Plot': 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.',
  'Language': 'English, Italian, Hebrew, Yiddish',
  'Country': 'United States',
  'Awards': 'Won 1 Oscar. 44 wins & 38 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.7/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '93%'},
   {'Source': 'Metacritic', 'Value': '92/100'}],
  'Metascore': '92',
  'imdbRating': '8.7',
  'imdbVotes': '1,350,647',
  'imdbID': 'tt0099685',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$46,909,721',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'GoodFellas'},
 {'Title': 'Lean on Me',
  'Year': '1989',
  'Rated': 'PG-13',
  'Released': '03 Mar 1989',
  'Runtime': '108 min',
  'Genre': 'Biography, Drama',
  'Director': 'John G. Avildsen',
  'Writer': 'Michael Schiffer',
  'Actors': 'Morgan Freeman, Beverly Todd, Robert Guillaume',
  'Plot': 'The dedicated but tyrannical Joe Clark is appointed the principal of a decaying inner-city school he is determined to improve by any and all means.',
  'Language': 'English, Spanish, Portuguese',
  'Country': 'United States',
  'Awards': '3 wins & 6 nominations',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BN2RmMzFkNDgtMjkxOC00NmRlLTlmNTgtYzkwYjdiYzZiZmU4XkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.4/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '71%'},
   {'Source': 'Metacritic', 'Value': '58/100'}],
  'Metascore': '58',
  'imdbRating': '7.4',
  'imdbVotes': '23,396',
  'imdbID': 'tt0097722',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$31,906,454',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Lean On Me'},
 {'Title': 'Eddie Murphy: Raw',
  'Year': '1987',
  'Rated': 'R',
  'Released': '18 Dec 1987',
  'Runtime': '93 min',
  'Genre': 'Documentary, Comedy',
  'Director': 'Robert Townsend',
  'Writer': 'Eddie Murphy, Keenen Ivory Wayans',
  'Actors': 'Eddie Murphy, Tatyana Ali, Billie Allen',
  'Plot': 'Eddie Murphy in a stand-up performance recorded live. For an hour and a half he talks about his favourite subjects: sex and women.',
  'Language': 'English',
  'Country': 'United States',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNTAxM2E4MGUtMGMyYS00ZGEyLThjMmQtNjQ1MmQ5ZTEyMzgyXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.6/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '79%'},
   {'Source': 'Metacritic', 'Value': '54/100'}],
  'Metascore': '54',
  'imdbRating': '7.6',
  'imdbVotes': '21,341',
  'imdbID': 'tt0092948',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$50,504,655',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Eddie Murphy Raw'},
 {'Title': 'Too Young the Hero',
  'Year': '1988',
  'Rated': 'Not Rated',
  'Released': '27 Mar 1988',
  'Runtime': '100 min',
  'Genre': 'Biography, Drama, War',
  'Director': 'Buzz Kulik',
  'Writer': 'Calvin Graham, Gary Thomas, David J. Kinghorn',
  'Actors': 'Ricky Schroder, Jon DeVries, Debra Mooney',
  'Plot': 'The true story of Calvin Graham who at the age of twelve, but looking quite a lot older, succeeded in joining the navy during World War II. In spite of his young age, he received a Purple Heart for his bravery in the Naval Battle ...',
  'Language': 'English',
  'Country': 'United States',
  'Awards': '2 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNDY4ZjEyOWItY2IzOC00NTI4LTk0MTEtNDNkYzYzMmYxMjRlXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.7/10'}],
  'Metascore': 'N/A',
  'imdbRating': '6.7',
  'imdbVotes': '593',
  'imdbID': 'tt0096286',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Too Young The Hero'},
 {'Title': 'Alexandria: Again and Forever',
  'Year': '1989',
  'Rated': 'Not Rated',
  'Released': '20 Jun 1990',
  'Runtime': '100 min',
  'Genre': 'Drama',
  'Director': 'Youssef Chahine',
  'Writer': 'Youssef Chahine, Yousry Nasrallah',
  'Actors': 'Youssra, Youssef Chahine, Hussein Fahmy',
  'Plot': 'During a hunger strike by the Egyptian film industry, Yehia, a famous Egyptian director, finds himself obsessed with Amir, the leading man in one of his movies, and Nadia, a woman he desires to work with.',
  'Language': 'Arabic',
  'Country': 'France, Egypt',
  'Awards': '1 win & 1 nomination',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMWYxNzdlOGYtOTliMC00Mzc1LWE4MjMtYjkxZjlhOWY3ZWQ1XkEyXkFqcGdeQXVyMjI4NzAzNjg@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.5/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '100%'}],
  'Metascore': 'N/A',
  'imdbRating': '6.5',
  'imdbVotes': '811',
  'imdbID': 'tt0099858',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Alexandria, Again and Forever'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'The Little Wars'},
 {'Title': 'Mission: Impossible - Ghost Protocol',
  'Year': '2011',
  'Rated': 'PG-13',
  'Released': '21 Dec 2011',
  'Runtime': '132 min',
  'Genre': 'Action, Adventure, Thriller',
  'Director': 'Brad Bird',
  'Writer': 'Bruce Geller, Josh Appelbaum, André Nemec',
  'Actors': 'Tom Cruise, Jeremy Renner, Simon Pegg',
  'Plot': "The IMF is shut down when it's implicated in the bombing of the Kremlin, causing Ethan Hunt and his new team to go rogue to clear their organization's name.",
  'Language': 'English, Russian, French, Arabic, Swedish',
  'Country': 'United States, United Arab Emirates, Russia, Canada, Czech Republic, India',
  'Awards': '5 wins & 30 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMTY4MTUxMjQ5OV5BMl5BanBnXkFtZTcwNTUyMzg5Ng@@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.4/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '94%'},
   {'Source': 'Metacritic', 'Value': '73/100'}],
  'Metascore': '73',
  'imdbRating': '7.4',
  'imdbVotes': '555,260',
  'imdbID': 'tt1229238',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$209,397,903',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Mission: Impossible'},
 {'Title': 'Inuyasha',
  'Year': '2000–2004',
  'Rated': 'TV-14',
  'Released': '31 Aug 2002',
  'Runtime': '24 min',
  'Genre': 'Animation, Action, Adventure',
  'Director': 'N/A',
  'Writer': 'Rumiko Takahashi',
  'Actors': 'Kappei Yamaguchi, Richard Ian Cox, Sarah Hauser',
  'Plot': 'A teenage girl periodically travels back in time to feudal Japan to help a young half-demon recover the shards of a jewel of great power.',
  'Language': 'Japanese',
  'Country': 'Japan',
  'Awards': '2 wins & 1 nomination total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BZjQxYThmNGEtNzU2ZS00NjZmLWEzNTItMWM2NmU0ZTc5NjY3XkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.9/10'}],
  'Metascore': 'N/A',
  'imdbRating': '7.9',
  'imdbVotes': '19,166',
  'imdbID': 'tt0290223',
  'Type': 'series',
  'totalSeasons': '7',
  'Response': 'True',
  'original_title': 'InuYasha'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'My First Errand'},
 {'Title': "Jerry Seinfeld: 'I'm Telling You for the Last Time'",
  'Year': '1998',
  'Rated': 'TV-14',
  'Released': '09 Aug 1998',
  'Runtime': '75 min',
  'Genre': 'Comedy',
  'Director': 'Marty Callner',
  'Writer': 'Jerry Seinfeld',
  'Actors': 'Jerry Seinfeld, Michael Barryte, Grace Bustos',
  'Plot': 'Live from New York City, Jerry Seinfeld, aided and abetted by a host of friends and fellow comedians, performs his 1998 Emmy-nominated performance on Broadway.',
  'Language': 'English',
  'Country': 'United States',
  'Awards': 'Nominated for 2 Primetime Emmys. 4 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNDM4OTY0NTAyMF5BMl5BanBnXkFtZTcwNTcxMDQyMQ@@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.8/10'}],
  'Metascore': 'N/A',
  'imdbRating': '7.8',
  'imdbVotes': '6,303',
  'imdbID': 'tt0500140',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': "Jerry Seinfeld: I'm Telling You for the Last Time"},
 {'Title': "Jaan-E-Mann: Let's Fall in Love... Again",
  'Year': '2006',
  'Rated': 'Not Rated',
  'Released': '20 Oct 2006',
  'Runtime': '165 min',
  'Genre': 'Comedy, Drama, Musical',
  'Director': 'Shirish Kunder',
  'Writer': 'Shirish Kunder',
  'Actors': 'Salman Khan, Akshay Kumar, Preity G Zinta',
  'Plot': 'Follows a love triangle between Agastya, Suhaan and Piya.',
  'Language': 'Hindi, English',
  'Country': 'India',
  'Awards': '2 nominations',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BZjVhMzNhZTEtMDRhMS00OTUyLTk1NDktYzUwN2U3ZWU0OGNhXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.1/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '50%'},
   {'Source': 'Metacritic', 'Value': '40/100'}],
  'Metascore': '40',
  'imdbRating': '6.1',
  'imdbVotes': '9,309',
  'imdbID': 'tt0456481',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$650,000',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Mann'},
 {'Title': 'The Sam Kinison Family Entertainment Hour',
  'Year': '1991',
  'Rated': 'Not Rated',
  'Released': '13 Jul 1991',
  'Runtime': '50 min',
  'Genre': 'Documentary, Comedy, Music',
  'Director': 'Walter C. Miller',
  'Writer': 'Sam Kinison',
  'Actors': 'Sam Kinison, Arthur Eckdahl, Randy Hansen',
  'Plot': "Catch Sam Kinison in his last recorded special. Filmed live at the Wiltern Theatre, Sam's not only provides the screaming comedy you've come to love him for, but he bookends this special with rock performances!",
  'Language': 'English',
  'Country': 'United States',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMTg5ODE3NDA2NV5BMl5BanBnXkFtZTcwMjUxNTEyMQ@@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.4/10'}],
  'Metascore': 'N/A',
  'imdbRating': '6.4',
  'imdbVotes': '318',
  'imdbID': 'tt0249934',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Sam Kinison: Family Entertainment Hour'},
 {'Title': 'Hum Saath-Saath Hain',
  'Year': '1999',
  'Rated': 'Not Rated',
  'Released': '05 Nov 1999',
  'Runtime': '177 min',
  'Genre': 'Drama, Musical',
  'Director': 'Sooraj R. Barjatya',
  'Writer': 'Sooraj R. Barjatya',
  'Actors': 'Mohnish Behl, Salman Khan, Saif Ali Khan',
  'Plot': 'Ramkishen and Mamta have three sons Vivek , Prem and Vinod and a daughter Sangeeta. This family is part of a joint family whose close knit bond is challenged by a misunderstanding.',
  'Language': 'Hindi',
  'Country': 'India',
  'Awards': '1 win & 6 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMTc2NDQ5OTIzNl5BMl5BanBnXkFtZTgwMTI5ODUzNzE@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.3/10'}],
  'Metascore': 'N/A',
  'imdbRating': '6.3',
  'imdbVotes': '10,224',
  'imdbID': 'tt0216817',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$2,005,094',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Hum Saath Saath Hain'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Monty Python: Live at Aspen'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Minsara Kanavu'},
 {'Title': 'Tim Allen Rewires America',
  'Year': '1991',
  'Rated': 'Not Rated',
  'Released': '07 Dec 1991',
  'Runtime': '30 min',
  'Genre': 'Documentary, Comedy',
  'Director': 'Ellen Brown',
  'Writer': 'Tim Allen',
  'Actors': 'Tim Allen',
  'Plot': 'In his second Showtime stand-up comedy special taped at The Power Center for the Performing Arts in Ann Arbor, Michigan, Tim Allen proudly grunts his way through a discussion of "men stuff."',
  'Language': 'English',
  'Country': 'United States',
  'Awards': '1 nomination',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BYzJhOTc0OWQtYWUzMC00ZjBiLTg1MTctZTc4ZDdhNjllYTJmXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [],
  'Metascore': 'N/A',
  'imdbRating': 'N/A',
  'imdbVotes': '219',
  'imdbID': 'tt0294967',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Tim Allen: Rewires America'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Bill Hicks: One Night Stand'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': "Sinbad: Nothin' but the Funk"},
 {'Title': 'Monty Python: Before the Flying Circus',
  'Year': '2008',
  'Rated': 'Not Rated',
  'Released': 'N/A',
  'Runtime': '55 min',
  'Genre': 'Documentary',
  'Director': 'Will Yapp',
  'Writer': 'N/A',
  'Actors': 'Robert Bathurst, Eric Idle, John Cleese',
  'Plot': "The pre-Monty Python years of the six members of the group. Covers their school and university days, their first individual forays into comedy, how the parts slowly came together and Monty Python's eventual formation.",
  'Language': 'English',
  'Country': 'United Kingdom',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMDM5MjA3YzEtOTE0ZS00NzVlLWE5NWEtZjdlMGUzNTg0NDVjXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.3/10'}],
  'Metascore': 'N/A',
  'imdbRating': '7.3',
  'imdbVotes': '218',
  'imdbID': 'tt9230920',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Before the Flying Circus'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Have You Ever Seen Fireflies? - Theatre Play'},
 {'Title': 'Death Note',
  'Year': '2006–2007',
  'Rated': 'TV-14',
  'Released': '21 Oct 2007',
  'Runtime': '24 min',
  'Genre': 'Animation, Crime, Drama',
  'Director': 'N/A',
  'Writer': 'N/A',
  'Actors': 'Mamoru Miyano, Brad Swaile, Vincent Tong',
  'Plot': 'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.',
  'Language': 'Japanese, English',
  'Country': 'Japan',
  'Awards': '2 wins & 1 nomination total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BYTgyZDhmMTEtZDFhNi00MTc4LTg3NjUtYWJlNGE5Mzk2NzMxXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.9/10'}],
  'Metascore': 'N/A',
  'imdbRating': '8.9',
  'imdbVotes': '440,716',
  'imdbID': 'tt0877057',
  'Type': 'series',
  'totalSeasons': '1',
  'Response': 'True',
  'original_title': 'DEATH NOTE'},
 {'Title': 'Blade Runner: The Final Cut (2007)',
  'Year': '2007',
  'Rated': 'N/A',
  'Released': '17 Sep 2018',
  'Runtime': 'N/A',
  'Genre': 'N/A',
  'Director': 'N/A',
  'Writer': 'N/A',
  'Actors': 'N/A',
  'Plot': 'N/A',
  'Language': 'N/A',
  'Country': 'N/A',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BM2M0NjUwNzktZWFiMy00NjMyLWE4MGQtMWRhZjY2MjQ4OTA2XkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [],
  'Metascore': 'N/A',
  'imdbRating': 'N/A',
  'imdbVotes': 'N/A',
  'imdbID': 'tt24742930',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Blade Runner: The Final Cut'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Apocalypse Now Redux'},
 {'Title': 'Transformers Prime',
  'Year': '2010–2013',
  'Rated': 'TV-Y7',
  'Released': '26 Nov 2010',
  'Runtime': '1 min',
  'Genre': 'Animation, Action, Adventure',
  'Director': 'N/A',
  'Writer': 'Duane Capizzi, Jeff Kline, Alex Kurtzman',
  'Actors': 'Peter Cullen, Sumalee Montano, Jeffrey Combs',
  'Plot': 'In this new set of adventures the Autobots live on Earth and maintain their secret identity. They are joined by 3 teens as they battle the Decepticons.',
  'Language': 'English',
  'Country': 'United States',
  'Awards': '14 wins & 26 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMjRiODgwNmYtZjk3Ny00YTFiLTgxM2MtNmVjMWEwZTNjYjkyXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.1/10'}],
  'Metascore': 'N/A',
  'imdbRating': '8.1',
  'imdbVotes': '9,765',
  'imdbID': 'tt1659175',
  'Type': 'series',
  'totalSeasons': '3',
  'Response': 'True',
  'original_title': 'Transformers: Prime'},
 {'Title': 'Code Geass: Lelouch of the Rebellion I - Initiation',
  'Year': '2017',
  'Rated': 'N/A',
  'Released': '21 Oct 2017',
  'Runtime': '135 min',
  'Genre': 'Animation, Action, Sci-Fi',
  'Director': 'Noriaki Akitaya, Gorô Taniguchi',
  'Writer': 'Gorô Taniguchi, Clamp, Ichirô Ôkouchi',
  'Actors': 'Jun Fukuyama, Takahiro Sakurai, Yukana',
  'Plot': 'A remake of first 17 episodes of code geass R1.',
  'Language': 'Japanese',
  'Country': 'Japan',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNjEyMzA0NDctNTQwMy00NDQ0LWExYjctOWYzMDcyYWYyMzFiXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.3/10'}],
  'Metascore': 'N/A',
  'imdbRating': '7.3',
  'imdbVotes': '789',
  'imdbID': 'tt8100900',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Code Geass: Lelouch of the Rebellion'},
 {'Response': 'False',
  'Error': 'Movie not found!',

In [46]:
def remove_request_limit_reached(data):
    try:
        if data['Error'] == 'Request limit reached!':
            return False
        elif data['Error'] == 'Movie not found!':
            return True
    except KeyError:
        return True


omdb_data_cleaned = [i for i in omdb_data if remove_request_limit_reached(i)]
len(omdb_data_cleaned)

1001

In [47]:
omdb_data_cleaned

[{'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Five Came Back: The Reference Films'},
 {'Title': "Monty Python's Life of Brian",
  'Year': '1979',
  'Rated': 'R',
  'Released': '17 Aug 1979',
  'Runtime': '94 min',
  'Genre': 'Comedy',
  'Director': 'Terry Jones',
  'Writer': 'Graham Chapman, John Cleese, Terry Gilliam',
  'Actors': 'Graham Chapman, John Cleese, Michael Palin',
  'Plot': 'Born on the original Christmas in the stable next door to Jesus Christ, Brian of Nazareth spends his life being mistaken for a messiah.',
  'Language': 'English, Latin',
  'Country': 'United Kingdom',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNDMzY2E4NjEtMTJiZC00Y2UzLWFiM2MtZWVhNTg5OGQxNjk1XkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.0/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '96%'},
   {'Source': 'Metacritic', 'Value': '77/100'}],
  'Metascore': '77',
  'imdbRating': '8.0',
  'imdbVotes': '430,381',
  'imdbID': 'tt0079470',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$20,206,622',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Life of Brian'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Alexandria… Why?'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Saladin the Victorious'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Beirut, Oh Beirut'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'The Return of the Prodigal Son'},
 {'Title': 'Goodfellas',
  'Year': '1990',
  'Rated': 'R',
  'Released': '21 Sep 1990',
  'Runtime': '145 min',
  'Genre': 'Biography, Crime, Drama',
  'Director': 'Martin Scorsese',
  'Writer': 'Nicholas Pileggi, Martin Scorsese',
  'Actors': 'Robert De Niro, Ray Liotta, Joe Pesci',
  'Plot': 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.',
  'Language': 'English, Italian, Hebrew, Yiddish',
  'Country': 'United States',
  'Awards': 'Won 1 Oscar. 44 wins & 38 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.7/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '93%'},
   {'Source': 'Metacritic', 'Value': '92/100'}],
  'Metascore': '92',
  'imdbRating': '8.7',
  'imdbVotes': '1,350,647',
  'imdbID': 'tt0099685',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$46,909,721',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'GoodFellas'},
 {'Title': 'Lean on Me',
  'Year': '1989',
  'Rated': 'PG-13',
  'Released': '03 Mar 1989',
  'Runtime': '108 min',
  'Genre': 'Biography, Drama',
  'Director': 'John G. Avildsen',
  'Writer': 'Michael Schiffer',
  'Actors': 'Morgan Freeman, Beverly Todd, Robert Guillaume',
  'Plot': 'The dedicated but tyrannical Joe Clark is appointed the principal of a decaying inner-city school he is determined to improve by any and all means.',
  'Language': 'English, Spanish, Portuguese',
  'Country': 'United States',
  'Awards': '3 wins & 6 nominations',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BN2RmMzFkNDgtMjkxOC00NmRlLTlmNTgtYzkwYjdiYzZiZmU4XkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.4/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '71%'},
   {'Source': 'Metacritic', 'Value': '58/100'}],
  'Metascore': '58',
  'imdbRating': '7.4',
  'imdbVotes': '23,396',
  'imdbID': 'tt0097722',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$31,906,454',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Lean On Me'},
 {'Title': 'Eddie Murphy: Raw',
  'Year': '1987',
  'Rated': 'R',
  'Released': '18 Dec 1987',
  'Runtime': '93 min',
  'Genre': 'Documentary, Comedy',
  'Director': 'Robert Townsend',
  'Writer': 'Eddie Murphy, Keenen Ivory Wayans',
  'Actors': 'Eddie Murphy, Tatyana Ali, Billie Allen',
  'Plot': 'Eddie Murphy in a stand-up performance recorded live. For an hour and a half he talks about his favourite subjects: sex and women.',
  'Language': 'English',
  'Country': 'United States',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNTAxM2E4MGUtMGMyYS00ZGEyLThjMmQtNjQ1MmQ5ZTEyMzgyXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.6/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '79%'},
   {'Source': 'Metacritic', 'Value': '54/100'}],
  'Metascore': '54',
  'imdbRating': '7.6',
  'imdbVotes': '21,341',
  'imdbID': 'tt0092948',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$50,504,655',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Eddie Murphy Raw'},
 {'Title': 'Too Young the Hero',
  'Year': '1988',
  'Rated': 'Not Rated',
  'Released': '27 Mar 1988',
  'Runtime': '100 min',
  'Genre': 'Biography, Drama, War',
  'Director': 'Buzz Kulik',
  'Writer': 'Calvin Graham, Gary Thomas, David J. Kinghorn',
  'Actors': 'Ricky Schroder, Jon DeVries, Debra Mooney',
  'Plot': 'The true story of Calvin Graham who at the age of twelve, but looking quite a lot older, succeeded in joining the navy during World War II. In spite of his young age, he received a Purple Heart for his bravery in the Naval Battle ...',
  'Language': 'English',
  'Country': 'United States',
  'Awards': '2 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNDY4ZjEyOWItY2IzOC00NTI4LTk0MTEtNDNkYzYzMmYxMjRlXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.7/10'}],
  'Metascore': 'N/A',
  'imdbRating': '6.7',
  'imdbVotes': '593',
  'imdbID': 'tt0096286',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Too Young The Hero'},
 {'Title': 'Alexandria: Again and Forever',
  'Year': '1989',
  'Rated': 'Not Rated',
  'Released': '20 Jun 1990',
  'Runtime': '100 min',
  'Genre': 'Drama',
  'Director': 'Youssef Chahine',
  'Writer': 'Youssef Chahine, Yousry Nasrallah',
  'Actors': 'Youssra, Youssef Chahine, Hussein Fahmy',
  'Plot': 'During a hunger strike by the Egyptian film industry, Yehia, a famous Egyptian director, finds himself obsessed with Amir, the leading man in one of his movies, and Nadia, a woman he desires to work with.',
  'Language': 'Arabic',
  'Country': 'France, Egypt',
  'Awards': '1 win & 1 nomination',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMWYxNzdlOGYtOTliMC00Mzc1LWE4MjMtYjkxZjlhOWY3ZWQ1XkEyXkFqcGdeQXVyMjI4NzAzNjg@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.5/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '100%'}],
  'Metascore': 'N/A',
  'imdbRating': '6.5',
  'imdbVotes': '811',
  'imdbID': 'tt0099858',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Alexandria, Again and Forever'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'The Little Wars'},
 {'Title': 'Mission: Impossible - Ghost Protocol',
  'Year': '2011',
  'Rated': 'PG-13',
  'Released': '21 Dec 2011',
  'Runtime': '132 min',
  'Genre': 'Action, Adventure, Thriller',
  'Director': 'Brad Bird',
  'Writer': 'Bruce Geller, Josh Appelbaum, André Nemec',
  'Actors': 'Tom Cruise, Jeremy Renner, Simon Pegg',
  'Plot': "The IMF is shut down when it's implicated in the bombing of the Kremlin, causing Ethan Hunt and his new team to go rogue to clear their organization's name.",
  'Language': 'English, Russian, French, Arabic, Swedish',
  'Country': 'United States, United Arab Emirates, Russia, Canada, Czech Republic, India',
  'Awards': '5 wins & 30 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMTY4MTUxMjQ5OV5BMl5BanBnXkFtZTcwNTUyMzg5Ng@@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.4/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '94%'},
   {'Source': 'Metacritic', 'Value': '73/100'}],
  'Metascore': '73',
  'imdbRating': '7.4',
  'imdbVotes': '555,260',
  'imdbID': 'tt1229238',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$209,397,903',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Mission: Impossible'},
 {'Title': 'Inuyasha',
  'Year': '2000–2004',
  'Rated': 'TV-14',
  'Released': '31 Aug 2002',
  'Runtime': '24 min',
  'Genre': 'Animation, Action, Adventure',
  'Director': 'N/A',
  'Writer': 'Rumiko Takahashi',
  'Actors': 'Kappei Yamaguchi, Richard Ian Cox, Sarah Hauser',
  'Plot': 'A teenage girl periodically travels back in time to feudal Japan to help a young half-demon recover the shards of a jewel of great power.',
  'Language': 'Japanese',
  'Country': 'Japan',
  'Awards': '2 wins & 1 nomination total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BZjQxYThmNGEtNzU2ZS00NjZmLWEzNTItMWM2NmU0ZTc5NjY3XkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.9/10'}],
  'Metascore': 'N/A',
  'imdbRating': '7.9',
  'imdbVotes': '19,166',
  'imdbID': 'tt0290223',
  'Type': 'series',
  'totalSeasons': '7',
  'Response': 'True',
  'original_title': 'InuYasha'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'My First Errand'},
 {'Title': "Jerry Seinfeld: 'I'm Telling You for the Last Time'",
  'Year': '1998',
  'Rated': 'TV-14',
  'Released': '09 Aug 1998',
  'Runtime': '75 min',
  'Genre': 'Comedy',
  'Director': 'Marty Callner',
  'Writer': 'Jerry Seinfeld',
  'Actors': 'Jerry Seinfeld, Michael Barryte, Grace Bustos',
  'Plot': 'Live from New York City, Jerry Seinfeld, aided and abetted by a host of friends and fellow comedians, performs his 1998 Emmy-nominated performance on Broadway.',
  'Language': 'English',
  'Country': 'United States',
  'Awards': 'Nominated for 2 Primetime Emmys. 4 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNDM4OTY0NTAyMF5BMl5BanBnXkFtZTcwNTcxMDQyMQ@@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.8/10'}],
  'Metascore': 'N/A',
  'imdbRating': '7.8',
  'imdbVotes': '6,303',
  'imdbID': 'tt0500140',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': "Jerry Seinfeld: I'm Telling You for the Last Time"},
 {'Title': "Jaan-E-Mann: Let's Fall in Love... Again",
  'Year': '2006',
  'Rated': 'Not Rated',
  'Released': '20 Oct 2006',
  'Runtime': '165 min',
  'Genre': 'Comedy, Drama, Musical',
  'Director': 'Shirish Kunder',
  'Writer': 'Shirish Kunder',
  'Actors': 'Salman Khan, Akshay Kumar, Preity G Zinta',
  'Plot': 'Follows a love triangle between Agastya, Suhaan and Piya.',
  'Language': 'Hindi, English',
  'Country': 'India',
  'Awards': '2 nominations',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BZjVhMzNhZTEtMDRhMS00OTUyLTk1NDktYzUwN2U3ZWU0OGNhXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.1/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '50%'},
   {'Source': 'Metacritic', 'Value': '40/100'}],
  'Metascore': '40',
  'imdbRating': '6.1',
  'imdbVotes': '9,309',
  'imdbID': 'tt0456481',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$650,000',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Mann'},
 {'Title': 'The Sam Kinison Family Entertainment Hour',
  'Year': '1991',
  'Rated': 'Not Rated',
  'Released': '13 Jul 1991',
  'Runtime': '50 min',
  'Genre': 'Documentary, Comedy, Music',
  'Director': 'Walter C. Miller',
  'Writer': 'Sam Kinison',
  'Actors': 'Sam Kinison, Arthur Eckdahl, Randy Hansen',
  'Plot': "Catch Sam Kinison in his last recorded special. Filmed live at the Wiltern Theatre, Sam's not only provides the screaming comedy you've come to love him for, but he bookends this special with rock performances!",
  'Language': 'English',
  'Country': 'United States',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMTg5ODE3NDA2NV5BMl5BanBnXkFtZTcwMjUxNTEyMQ@@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.4/10'}],
  'Metascore': 'N/A',
  'imdbRating': '6.4',
  'imdbVotes': '318',
  'imdbID': 'tt0249934',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Sam Kinison: Family Entertainment Hour'},
 {'Title': 'Hum Saath-Saath Hain',
  'Year': '1999',
  'Rated': 'Not Rated',
  'Released': '05 Nov 1999',
  'Runtime': '177 min',
  'Genre': 'Drama, Musical',
  'Director': 'Sooraj R. Barjatya',
  'Writer': 'Sooraj R. Barjatya',
  'Actors': 'Mohnish Behl, Salman Khan, Saif Ali Khan',
  'Plot': 'Ramkishen and Mamta have three sons Vivek , Prem and Vinod and a daughter Sangeeta. This family is part of a joint family whose close knit bond is challenged by a misunderstanding.',
  'Language': 'Hindi',
  'Country': 'India',
  'Awards': '1 win & 6 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMTc2NDQ5OTIzNl5BMl5BanBnXkFtZTgwMTI5ODUzNzE@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.3/10'}],
  'Metascore': 'N/A',
  'imdbRating': '6.3',
  'imdbVotes': '10,224',
  'imdbID': 'tt0216817',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$2,005,094',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Hum Saath Saath Hain'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Monty Python: Live at Aspen'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Minsara Kanavu'},
 {'Title': 'Tim Allen Rewires America',
  'Year': '1991',
  'Rated': 'Not Rated',
  'Released': '07 Dec 1991',
  'Runtime': '30 min',
  'Genre': 'Documentary, Comedy',
  'Director': 'Ellen Brown',
  'Writer': 'Tim Allen',
  'Actors': 'Tim Allen',
  'Plot': 'In his second Showtime stand-up comedy special taped at The Power Center for the Performing Arts in Ann Arbor, Michigan, Tim Allen proudly grunts his way through a discussion of "men stuff."',
  'Language': 'English',
  'Country': 'United States',
  'Awards': '1 nomination',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BYzJhOTc0OWQtYWUzMC00ZjBiLTg1MTctZTc4ZDdhNjllYTJmXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [],
  'Metascore': 'N/A',
  'imdbRating': 'N/A',
  'imdbVotes': '219',
  'imdbID': 'tt0294967',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Tim Allen: Rewires America'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Bill Hicks: One Night Stand'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': "Sinbad: Nothin' but the Funk"},
 {'Title': 'Monty Python: Before the Flying Circus',
  'Year': '2008',
  'Rated': 'Not Rated',
  'Released': 'N/A',
  'Runtime': '55 min',
  'Genre': 'Documentary',
  'Director': 'Will Yapp',
  'Writer': 'N/A',
  'Actors': 'Robert Bathurst, Eric Idle, John Cleese',
  'Plot': "The pre-Monty Python years of the six members of the group. Covers their school and university days, their first individual forays into comedy, how the parts slowly came together and Monty Python's eventual formation.",
  'Language': 'English',
  'Country': 'United Kingdom',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMDM5MjA3YzEtOTE0ZS00NzVlLWE5NWEtZjdlMGUzNTg0NDVjXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.3/10'}],
  'Metascore': 'N/A',
  'imdbRating': '7.3',
  'imdbVotes': '218',
  'imdbID': 'tt9230920',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Before the Flying Circus'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Have You Ever Seen Fireflies? - Theatre Play'},
 {'Title': 'Death Note',
  'Year': '2006–2007',
  'Rated': 'TV-14',
  'Released': '21 Oct 2007',
  'Runtime': '24 min',
  'Genre': 'Animation, Crime, Drama',
  'Director': 'N/A',
  'Writer': 'N/A',
  'Actors': 'Mamoru Miyano, Brad Swaile, Vincent Tong',
  'Plot': 'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.',
  'Language': 'Japanese, English',
  'Country': 'Japan',
  'Awards': '2 wins & 1 nomination total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BYTgyZDhmMTEtZDFhNi00MTc4LTg3NjUtYWJlNGE5Mzk2NzMxXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.9/10'}],
  'Metascore': 'N/A',
  'imdbRating': '8.9',
  'imdbVotes': '440,716',
  'imdbID': 'tt0877057',
  'Type': 'series',
  'totalSeasons': '1',
  'Response': 'True',
  'original_title': 'DEATH NOTE'},
 {'Title': 'Blade Runner: The Final Cut (2007)',
  'Year': '2007',
  'Rated': 'N/A',
  'Released': '17 Sep 2018',
  'Runtime': 'N/A',
  'Genre': 'N/A',
  'Director': 'N/A',
  'Writer': 'N/A',
  'Actors': 'N/A',
  'Plot': 'N/A',
  'Language': 'N/A',
  'Country': 'N/A',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BM2M0NjUwNzktZWFiMy00NjMyLWE4MGQtMWRhZjY2MjQ4OTA2XkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [],
  'Metascore': 'N/A',
  'imdbRating': 'N/A',
  'imdbVotes': 'N/A',
  'imdbID': 'tt24742930',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Blade Runner: The Final Cut'},
 {'Response': 'False',
  'Error': 'Movie not found!',
  'original_title': 'Apocalypse Now Redux'},
 {'Title': 'Transformers Prime',
  'Year': '2010–2013',
  'Rated': 'TV-Y7',
  'Released': '26 Nov 2010',
  'Runtime': '1 min',
  'Genre': 'Animation, Action, Adventure',
  'Director': 'N/A',
  'Writer': 'Duane Capizzi, Jeff Kline, Alex Kurtzman',
  'Actors': 'Peter Cullen, Sumalee Montano, Jeffrey Combs',
  'Plot': 'In this new set of adventures the Autobots live on Earth and maintain their secret identity. They are joined by 3 teens as they battle the Decepticons.',
  'Language': 'English',
  'Country': 'United States',
  'Awards': '14 wins & 26 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMjRiODgwNmYtZjk3Ny00YTFiLTgxM2MtNmVjMWEwZTNjYjkyXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.1/10'}],
  'Metascore': 'N/A',
  'imdbRating': '8.1',
  'imdbVotes': '9,765',
  'imdbID': 'tt1659175',
  'Type': 'series',
  'totalSeasons': '3',
  'Response': 'True',
  'original_title': 'Transformers: Prime'},
 {'Title': 'Code Geass: Lelouch of the Rebellion I - Initiation',
  'Year': '2017',
  'Rated': 'N/A',
  'Released': '21 Oct 2017',
  'Runtime': '135 min',
  'Genre': 'Animation, Action, Sci-Fi',
  'Director': 'Noriaki Akitaya, Gorô Taniguchi',
  'Writer': 'Gorô Taniguchi, Clamp, Ichirô Ôkouchi',
  'Actors': 'Jun Fukuyama, Takahiro Sakurai, Yukana',
  'Plot': 'A remake of first 17 episodes of code geass R1.',
  'Language': 'Japanese',
  'Country': 'Japan',
  'Awards': 'N/A',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNjEyMzA0NDctNTQwMy00NDQ0LWExYjctOWYzMDcyYWYyMzFiXkEyXkFqcGc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.3/10'}],
  'Metascore': 'N/A',
  'imdbRating': '7.3',
  'imdbVotes': '789',
  'imdbID': 'tt8100900',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True',
  'original_title': 'Code Geass: Lelouch of the Rebellion'},
 {'Response': 'False',
  'Error': 'Movie not found!',

In [48]:
omdb_data_cleaned_df = pd.read_json(json.dumps(omdb_data_cleaned))
omdb_data_cleaned_df.to_csv('/home/jasonzelin/data-analytics-portfolio/[in_progress]_netflix_data_etl_on_gcp/data/omdb_data_batch1.csv', index=False)
omdb_data_cleaned_df

/tmp/ipykernel_12787/1116496920.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  omdb_data_cleaned_df = pd.read_json(json.dumps(omdb_data_cleaned))

,Response,Error,original_title,Title,Year,Rated,Released,Runtime,Genre,Director,...,Metascore,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,totalSeasons
0,False,Movie not found!,Five Came Back: The Reference Films,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,True,NaN,Life of Brian,Monty Python's Life of Brian,1979,R,17 Aug 1979,94 min,Comedy,Terry Jones,...,77,8.0,"430,381",tt0079470,movie,N/A,"$20,206,622",N/A,N/A,NaN
2,False,Movie not found!,Alexandria… Why?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,False,Movie not found!,Saladin the Victorious,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,False,Movie not found!,"Beirut, Oh Beirut",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,True,NaN,The Forest,The Forest,2016,PG-13,08 Jan 2016,93 min,"Horror, Mystery, Thriller",Jason Zada,...,34,4.8,"46,521",tt3387542,movie,N/A,"$26,594,261",N/A,N/A,NaN
997,True,NaN,Cable Girls,Cable Girls,2017–2020,TV-MA,28 Apr 2017,1 min,"Drama, History",N/A,...,N/A,7.5,"17,173",tt5674718,series,NaN,NaN,NaN,NaN,5
998,False,Movie not found!,Jim & Andy: The Great Beyond - Featuring a Ver...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,True,NaN,A-X-L,A-X-L,2018,PG,24 Aug 2018,98 min,"Action, Adventure, Drama",Oliver Daly,...,29,5.3,"14,179",tt5709188,movie,N/A,"$6,501,381",N/A,N/A,NaN
1000,True,NaN,Hell Fest,Hell Fest,2018,R,28 Sep 2018,89 min,"Horror, Mystery, Thriller",Gregory Plotkin,...,26,5.5,"20,518",tt1999890,movie,N/A,"$11,107,431",N/A,N/A,NaN

In [66]:
omdb_data_cleaned_csv = pd.DataFrame()
parent_dir = '/home/jasonzelin/data-analytics-portfolio/[in_progress]_netflix_data_etl_on_gcp/data/'
files = os.listdir(parent_dir)
for file in files:
    if file.startswith('omdb_data_batch') and file.endswith('.csv'):
        temp_df = pd.read_csv(f'{parent_dir}{file}')
        omdb_data_cleaned_csv = pd.concat([omdb_data_cleaned_csv, temp_df], ignore_index=True)

def fill_title(row):
    if (pd.isnull(row['omdb_title'])) & (row['Error'] == 'Movie not found!'):
        return row['original_title']
    else:
        return row['omdb_title']

comparison_df = df_titles.merge(right=omdb_data_cleaned_csv, how='left', left_on='title', right_on='original_title').rename(columns={'Title': 'omdb_title'})
comparison_df = comparison_df.assign(omdb_title = lambda x: x.apply(fill_title, axis=1))
comparison_df

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,...,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Website,totalSeasons,Unnamed: 0
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,...,8.2,"989,092",tt0075314,movie,NaN,"$28,262,574",NaN,NaN,NaN,0.0
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,"['drama', 'action', 'thriller', 'european']",['US'],NaN,...,7.6,"125,930",tt0068473,movie,NaN,NaN,NaN,NaN,NaN,1.0
3,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['fantasy', 'action', 'comedy']",['GB'],NaN,...,8.2,"593,325",tt0071853,movie,NaN,"$2,562,392",NaN,NaN,NaN,2.0
4,tm120801,The Dirty Dozen,MOVIE,12 American military prisoners in World War II...,1967,NaN,150,"['war', 'action']","['GB', 'US']",NaN,...,7.7,"82,152",tt0061578,movie,NaN,NaN,NaN,NaN,NaN,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5859,tm1014599,Fine Wine,MOVIE,A beautiful love story that can happen between...,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5860,tm898842,C/O Kaadhal,MOVIE,A heart warming film that explores the concept...,2021,NaN,134,['drama'],[],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5861,tm1059008,Lokillo,MOVIE,A controversial TV host and comedian who has b...,2021,NaN,90,['comedy'],['CO'],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5862,tm1035612,Dad Stop Embarrassing Me - The Afterparty,MOVIE,"Jamie Foxx, David Alan Grier and more from the...",2021,PG-13,37,[],['US'],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5863,ts271048,Mighty Little Bheem: Kite Festival,SHOW,"With winter behind them, Bheem and his townspe...",2021,NaN,7,"['family', 'animation', 'comedy']",[],1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
print(f'{comparison_df[comparison_df['omdb_title'].isnull()].shape[0]} titles out of {comparison_df.shape[0]} from titles.csv still missing from OMDB API data.')

3946 titles out of 5864 from titles.csv still missing from OMDB API data.

In [68]:
missing_titles = comparison_df[comparison_df['omdb_title'].isnull()]['title'].tolist()
print(missing_titles)

['Aggretsuko', 'Malevolent', 'Jack Whitehall: Travels with My Father', 'Two Sentence Horror Stories', 'Dirty Money', 'Requiem', 'The Rain', "Sunderland 'Til I Die", 'Happy as Lazzaro', 'Nailed It!', 'My Mister', 'Bakugan: Battle Planet', 'Everybody Knows', 'Dave Chappelle', 'Damnation', 'Innocent', 'Great News', '22 July', 'Falls Around Her', 'Better Than Us', 'Insatiable', 'Sand Castle', 'Zoids Wild', 'Explained', "Buster's Mal Heart", 'The Toys That Made Us', 'On Body and Soul', 'Ben Is Back', 'Perfume', 'Mr. Sunshine', 'Private Life', 'Mirage', 'Ravenous', 'RBG', 'An Evening with Beverly Luff Linn', 'Friends from College', 'Mary Magdalene', 'Disjointed', 'Sisters', "Dumplin'", 'Tau', 'Creeped Out', 'Skins', 'Wormwood', 'Duck Butter', 'Never Stop Dreaming: The Life and Legacy of Shimon Peres', "The Zookeeper's Wife", 'Game Over, Man!', 'Polly Pocket', 'Steve Martin and Martin Short: An Evening You Will Forget for the Rest of Your Life', 'Victoria & Abdul', 'Hampstead', 'Hannah Gadsby: Nanette', 'War Machine', 'Bad Genius', 'Norm Macdonald Has a Show', 'Kakegurui', 'Al Hayba', 'The Kissing Booth', 'Tidelands', 'The Forgiven', 'Gypsy', 'King of Thieves', 'Minecraft: Story Mode', 'The Titan', 'Security', 'Transformers: Cyberverse', 'Mowgli: Legend of the Jungle', 'Abstract: The Art of Design', 'A Futile and Stupid Gesture', 'White Gold', 'How It Ends', 'Wanderlust', 'The Boss Baby: Back in Business', 'The After Party', 'Perfect Bid: The Contestant Who Knew Too Much', 'The Other Side of the Wind', 'Unauthorized Living', 'To the Bone', 'Goon: Last of the Enforcers', 'The Innocent Man', 'Unit 42', 'Numberblocks', 'Hot Girls Wanted: Turned On', 'We the Animals', 'Reversing Roe', 'Beyond Skyline', 'VeggieTales in the City', 'Valor', 'The Bar', 'The Hollow', 'Errementari: The Blacksmith and the Devil', 'Illang: The Wolf Brigade', 'Shirkers', 'A Bad Moms Christmas', 'B: The Beginning', 'Hotel Transylvania: The Series', 'Welcome Home', 'The Hook Up Plan', 'Piercing', 'The Outsider', 'Car Masters: Rust to Riches', 'Indian Horse', 'On My Block', 'Spy Kids: Mission Critical', 'Andhadhun', 'Unicorn Store', 'Hot Date', 'My Happy Family', 'Paradise PD', 'Newness', 'Monster High: Electrified', 'No Escape Room', 'Somewhere Between', 'Baby', 'Sick Note', "Hitler's Circle of Evil", 'Haunted', 'If I Leave Here Tomorrow: A Film About Lynyrd Skynyrd', 'Immortals', 'The Week Of', 'iBoy', 'The Standups', 'May the Devil Take You', 'The Bride of Habaek', 'The Breaker Upperers', 'When Heroes Fly', 'El Chapo', "If I Hadn't Met You", 'What the Health', 'Hi Score Girl', 'The Long Dumb Road', 'Long Shot', 'Dude', 'The Debt Collector', 'Sugar Rush', 'The Casketeers', 'Handsome Devil', 'Win It All', 'Tottaa Pataaka Item Maal', 'Trolls Holiday', 'Joan Didion: The Center Will Not Hold', 'The Guest', 'The Incredible Jessica James', 'Siberia', 'Ugly Delicious', 'The Resistance Banker', 'John Mulaney: Kid Gorgeous at Radio City', 'Girlboss', 'Because This Is My First Life', 'Just Between Lovers', 'The Saint', 'In Darkness', 'The Innocents', 'Transformers: Rescue Bots Academy', 'Bill Nye Saves the World', 'I Am a Killer', 'Sierra Burgess Is a Loser', 'Sad Hill Unearthed', 'Ibiza', 'Shimmer Lake', 'Suburra: Blood on Rome', 'Hey Arnold! The Jungle Movie', 'Tabula Rasa', 'Spirit: Riding Free', 'Little Witch Academia', 'Fullmetal Alchemist', 'Animal World', 'The Protector', 'Wheelman', 'Pop Team Epic', 'Voice', 'Cristela Alonzo: Lower Classy', 'Brain on Fire', 'Patriot Act with Hasan Minhaj', 'Bleach', 'The Epic Tales of Captain Underpants', 'The Mire', 'You Get Me', 'Rotten', 'Murder Mountain', 'My Teacher, My Obsession', 'Voyeur', 'Bathtubs Over Broadway', 'Scissor Seven', 'Psychokinesis', 'Alexa & Katie', 'Chip and Potato', 'Adam Sandler: 100% Fresh', 'Girl from Nowhere', 'Girl', 'The Polka King', 'The House of Flowers', 'Blame!', 'First They Killed My Father', 'The Magic School Bus Rides Again', 'MFKZ', 'The Worst Witch', 'Dogs', 'Magic for Humans', 'QB1: Beyond the Lights', 'Show Dogs', 'Black Earth Rising', '7 Days Out', "Girlfriend's Day", 'Welcome to the Family', 'The Resurrection of Gavin Stone', '3Below: Tales of Arcadia', 'A Love So Beautiful', 'Millennials', 'One of Us', 'Taylor Swift: Reputation Stadium Tour', 'Cathedral of the Sea', 'Signs', 'Bonus Family', 'Nicky Jam: El Ganador', 'Godzilla: Planet of the Monsters', 'Like Father', 'Fireworks', 'Godzilla: The Planet Eater', 'Amar', 'Birth of the Dragon', 'Outside In', 'Borderliner', 'Camarón Revolution', 'Lu Over the Wall', 'Memories of the Alhambra', 'Irreplaceable You', 'Chosen', 'The Royal House of Windsor', 'The Confession Tapes', 'Ad Vitam', 'Sandy Wexler', 'Alex Strangelove', 'Gaga: Five Foot Two', 'Free Rein', 'The Indian Detective', 'Sacred Games', 'Get Me Roger Stone', 'The Queen of Flow', "River's Edge", 'Dogs of Berlin', 'Animal Crackers', 'Meteor Garden', 'Shot in the Dark', 'Rainbow Rangers', 'Unsolved: The Murders of Tupac and The Notorious B.I.G.', 'Daniel Sloss: Live Shows', 'The Beauty Inside', 'Cry Babies Magic Tears', 'Love Daily', 'Mr. Roosevelt', 'Clive Davis: The Soundtrack of Our Lives', 'The Mechanism', 'Ricky Gervais: Humanity', 'Lady J', 'Thus Spoke Kishibe Rohan', 'The Christmas Chronicles', 'The Photographer of Mauthausen', 'Bill Nye: Science Guy', 'Welcome to Waikiki', 'Quincy', 'Thieves of the Wood', 'Blood Pact', 'Cuba and the Cameraman', 'The World Is Yours', 'Final Fantasy XIV: Dad of Light', 'Toc Toc', 'Fate/Apocrypha', 'Greenhouse Academy', 'Champions', 'Cleo & Cuquin', 'Acts of Vengeance', 'Carrie Pilby', 'The Clapper', 'Fun Mom Dinner', 'The Land of Steady Habits', 'November 13: Attack on Paris', "Okko's Inn", 'SKY Castle', 'Our Souls at Night', 'Man Like Mobeen', 'BuyBust', "Escape from Mr. Lemoncello's Library", 'I Am Jonas', 'Life Sentence', 'MILF', 'Springsteen On Broadway', 'Solo', 'Bullet Head', 'Small Crimes', 'Unrest', 'Ingobernable', 'Eternal Love', 'Take the Ball, Pass the Ball', 'Ashes of Love', 'Lawless Lawyer', 'Cyborg 009: Call of Justice', 'Reprisal', 'The Princess Switch', 'High Society', 'Gormiti', 'The Ottoman Lieutenant', 'Whose Streets?', 'The Open House', 'The A List', 'Trevor Noah: Son of Patricia', 'Little Evil', 'Beyblade Burst Turbo', 'The Curious Creations of Christine McConnell', 'Clean with Passion for Now', 'GHOUL', 'Christmas with a Prince', "Norm Macdonald: Hitler's Dog, Gossip & Trickery", 'Kiss Me First', 'Barbie: Dreamhouse Adventures', 'Diablero', 'Erased', 'Instant Hotel', 'Bending the Arc', 'Day of the Dead: Bloodline', 'Monkey Twins', 'Retablo', 'A Korean Odyssey', "John Leguizamo's Latin History for Morons", 'Power Rangers Ninja Steel', 'Warrior', 'Orbiter 9', 'White Fang', 'Life', 'Sand Storm', 'Generation Iron 3', 'Jo Koy: Live from Seattle', 'Oh, Hello on Broadway', 'Camarón: The Film', 'The Outcasts', 'Something in the Rain', 'Gnome Alone', '13 Reasons Why: Beyond the Reasons', 'How to Be Really Bad', "Julie's Greenroom", 'Prison Playbook', 'The Angel', 'Brainchild', 'Apaches', 'Father of the Year', "The B-Side: Elsa Dorfman's Portrait Photography", 'Puss in Book: Trapped in an Epic Tale', 'Demetri Martin: The Overthinker', 'The Death and Life of Marsha P. Johnson', 'Revolutionary Love', 'Happy Anniversary', 'Dope', 'Neo Yokio', 'Dry Martina', 'El Camino Christmas', 'Crazy Delicious', 'Marlon', 'Bumping Mics with Jeff Ross & Dave Attell', 'The Fix', 'Bobby Kennedy for President', 'The Legacy of a Whitetail Deer Hunter', 'Clinical', 'Godzilla: City on the Edge of Battle', 'The Yard', 'Familiar Wife', 'Medal of Honor', 'Llama Llama', 'My Masterpiece', 'Ronnie Coleman: The King', 'True and the Rainbow Kingdom', 'Hasan Minhaj: Homecoming King', 'The Climb', 'Secret Superstar', 'Wolf', 'Back Street Girls -GOKUDOLS-', 'A Twelve-Year Night', 'Dear Ex', 'Ultimate Beastmaster', 'The Piano Forest', 'WHAT DID JACK DO?', 'Flavors of Youth', 'Burn Out', 'Victim Number 8', 'Modest Heroes', 'Jenni Rivera: Mariposa de Barrio', 'Iliza Shlesinger: Elder Millennial', 'Sirius the Jaeger', 'The Seven Deadly Sins: Prisoners of the Sky', 'Kakegurui', 'The Battleship Island', 'Sanju', 'Ultraviolet', 'Point Blank', "Ron White: If You Quit Listening, I'll Shut Up", 'Craig Ferguson: Tickle Fight', 'Sarkar', 'Casting JonBenet', "They'll Love Me When I'm Dead", 'Strong Island', 'Come Sunday', 'The Most Hated Woman in America', 'Lommbock', 'The Final Table', 'Time: The Kalief Browder Story', 'Aya', 'Wedding Unplanned', 'Trump: An American Dream', 'Spyder', 'The New Legends of Monkey', 'The Killer', 'Lust Stories', 'Robot Trains', 'The Most Unknown', 'Flint Town', 'The Motive', 'Mercury 13', 'Vai Anitta', 'Eerie', 'The Inmate', 'Death by Magic', 'The Day I Met El Chapo: The Kate del Castillo Story', 'Tig Notaro: Happy To Be Here', 'Benji', 'The Little Vampire 3D', 'Time Share', 'Surviving Escobar - Alias JJ', 'My Sassy Girl', 'Lego Jurassic World: The Secret Exhibit', 'Beyond Stranger Things', 'Rip Tide', 'Holy Camp!', 'Samurai Gourmet', 'Alaska Is a Drag', 'Mob Psycho 100', 'Parmanu: The Story of Pokhran', 'Zero', 'Castle and Castle', 'Amateur', 'Pottersville', 'Re: Mind', 'A Christmas Prince: The Royal Wedding', 'The Bleeding Edge', 'Lowriders', 'Becoming Champions', 'Derren Brown: The Push', 'The Warning', 'Hero Mask', 'Yummy Mummies', 'NY Prison Break: The Seduction of Joyce Mitchell', 'S.W.A.T.: Under Siege', 'Live', 'Wild District', 'Selection Day', '6 Balloons', 'Chasing Coral', 'Next Gen', 'Trailer Park Boys: Out of the Park: USA', 'The Big Family Cooking Showdown', 'Ram Dass, Going Home', "Edgar Rice Burroughs' Tarzan and Jane", 'First Match', "Sunday's Illness", 'I Am Not an Easy Man', 'Justice', "Seth Rogen's Hilarity for Charity", 'Charming', 'Falsa identidad', 'Christmas Wedding Planner', 'Budapest', '44 Cats', 'All I Wish', 'Strongest Deliveryman', 'Angamaly Diaries', 'ReMastered: Tricky Dick & The Man in Black', 'Live Up To Your Name', 'Ingress: The Animation', 'Fred Armisen: Standup for Drummers', 'Thi Mai', 'Fastest Car', 'Battle', 'Bad Guys: Vile City', 'Holy Goalie', 'Saving Capitalism', 'The Platform', 'Bibi & Tina: Perfect Pandemonium', 'The Degenerates', 'Mom', 'Children of the Whales', 'Christmas Inheritance', 'An Imperfect Murder', 'LEGO Marvel Super Heroes: Guardians of the Galaxy - The Thanos Threat', 'Killing Hasselhoff', 'The Rise of Phoenixes', 'Shepherds and Butchers', 'The Skin of the Wolf', 'The Holiday Calendar', 'Zac & Mia', 'Deidra & Laney Rob a Train', 'Sahara', 'Take Your Pills', 'And Breathe Normally', 'Abby Hatcher', 'My Only Love Song', 'A Little Help with Carol Burnett', 'ReBoot: The Guardian Code', 'Naked', 'Secret Agent Selection: WW2', 'Love and Fortune', 'Drug Lords', 'The Invisible Guardian', 'Fate/Extra Last Encore', 'Jim Jefferies: This Is Me Now', 'Cities of Last Things', "Si saben cómo me pongo ¿Pa' qué me invitan?", 'Luis Miguel: The Series', "It's for Your Own Good", 'Busted!', 'The Laws of Thermodynamics', 'Boca Juniors Confidential', 'Handsome: A Netflix Mystery Movie', 'Dinotrux: Supercharged', 'Hometown Holiday', 'Inside the Criminal Mind', 'Jailbreak', 'Roxanne, Roxanne', 'Quién te cantará', 'Something Huge', 'Sparta', 'Lucid Dream', 'Carbone', 'Bhavesh Joshi Superhero', 'Nothing to Hide', 'A.I.C.O. -Incarnation-', 'The Awakening of Motti Wolkenbruch', 'Luo Bao Bei', 'My Shy Boss', '100 Days My Prince', 'Afflicted', 'Bill Burr: Walk Your Way Out', 'Dancing Queen', 'Million Yen Women', 'Fugitiva', 'The Legend of Cocaine Island', 'Barbie: Dolphin Magic', 'Birdshot', 'Pucca: Love Recipe', 'Steel Rain', 'Christmas with a View', 'A Miraculous Christmas Special: Tales of Ladybug and Cat Noir', 'Greg Davies: You Magnificent Beast', 'Relatable', 'Catfight', 'Paradise Lost', "Ali's Wedding", 'Toilet: A Love Story', 'When Angels Sleep', '72 Dangerous Animals: Asia', 'The Stolen', 'Perú: Tesoro Escondido', 'Break', 'My Dead Ex', 'Misty', 'Black Is Beltza', 'Terrorism Close Calls', 'Edge of Fear', 'My ID is Gangnam Beauty', 'Girls Incarcerated', 'Ryan Hamilton: Happy Face', 'End Game', 'Bad Seeds', 'Smoking', 'Shéhérazade', 'The Mansion', 'Yucatán', 'Mike Birbiglia: Thank God for Jokes', 'Us and Them', 'Pad Man', 'On My Skin', 'Sun Dogs', 'Derren Brown: Miracle', 'Manto', 'Little Boxes', 'Move', 'Raising the Bar', 'Hymn of Death', 'Bomb Scared', 'Terrace House: Opening New Doors', 'Undercover Law', 'Baazaar', 'Ittefaq', 'Myths & Monsters', 'Giant', 'Chris Rock: Tamborine', '72 Dangerous Animals: Latin America', 'Take Me', 'Ee Nagaraniki Emaindi', 'Patton Oswalt: Annihilation', 'LEGO Marvel Super Heroes: Black Panther - Trouble in Wakanda', 'Rory Scovel Tries Stand-Up for the First Time', 'Revenger', 'The Crossing', 'Coin Heist', 'RIDE ON TIME', 'Bitter Daisies', 'LEGO Friends: Girls on a Mission', 'Joy', 'Hakkunde', 'Jagga Jasoos', 'The Joel McHale Show with Joel McHale', 'Getaway Plan', 'The Velvet Collection', 'The Drug King', 'Jab Harry Met Sejal', 'Katt Williams: Great America', 'Derren Brown: Sacrifice', 'Kibaoh Klashers', 'Struggle: The Life and Lost Art of Szukalski', 'Sky Ladder: The Art of Cai Guo-Qiang', 'The Fortress', 'Qarib Qarib Singlle', 'Last Hope', 'My Secret Romance', 'Disconnect', 'Feminists: What Were They Thinking?', 'Duck Duck Goose', 'A Christmas Prince', 'Azali', 'Ainori Love Wagon: Asian Journey', 'All About the Washingtons', 'All Hail King Julien: Exiled', 'The Who Was? Show', 'Switched', 'Aiyaary', 'Kantaro: The Sweet Tooth Salaryman', 'Legend Quest', 'Ask the Doctor', 'SPF-18', 'Kulipari: Dream Walker', 'Hari Kondabolu: Warn Your Relatives', 'Seeing Allred', 'Resurface', 'Heroin(e)', 'Empire Games', 'The Tribe', 'The Plagues of Breslau', 'Sudani from Nigeria', 'Pope Francis: A Man of His Word', 'Candy Jar', 'Neal Brennan: 3 Mics', 'FIGHTWORLD', 'To Each, Her Own', "Kuroko's Basketball the Movie: Last Game", 'Rock my Heart', 'Mersal', 'Jerry Before Seinfeld', 'The Last Shaman', 'All Good', 'Bareilly Ki Barfi', 'First Team: Juventus', 'Expedition Happiness', 'Dany Boon: Des Hauts-De-France', 'Baadshaho', 'Edha', 'Rapture', 'C/o Kancharapalem', 'Black Crows', 'Super Drags', 'Battlefish', 'Jack Whitehall: At Large', 'The Rachel Divide', 'Trevor Noah: Afraid of the Dark', 'The Tree of Blood', 'Nothing to Lose', 'SWORDGAI The Animation', 'Larva Island', 'Accidentally In Love', 'Spivak', 'Love, Surreal and Odd', 'Jefe', 'Million Pound Menu', 'Christmas in the Heartland', 'Sir', 'The Break with Michelle Wolf', 'Jim Gaffigan: Cinco', 'Half Girlfriend', 'Daughters of Destiny', 'Ex-Shaman', 'The American Meme', 'Amazing Interiors', 'The Comedy Lineup', 'The Art of Loving: Story of Michalina Wislocka', "Paul Hollywood's Big Continental Road Trip", 'Titipo Titipo', 'Dovlatov', 'Borges', 'Stretch Armstrong & the Flex Fighters', 'El testigo', '1983', 'Weed the People', 'Maktub', 'Love per Square Foot', 'Wrong Kind of Black', 'Harvey Street Kids', 'Stay Here', 'Perdida', 'Serial Killer with Piers Morgan', 'The Girl from the Song', 'Going for Gold', 'Mubarakan', 'Dragon Pilot: Hisone and Masotan', 'Blazing Transfer Students', 'Argon', 'Qismat', 'Fire Chasers', "Sara's Notebook", 'Ali Wong: Hard Knock Wife', 'Tom Segura: Disgraceful', 'Limitless', 'AMO', 'Unrequited Love', 'Paskal', 'The Grown-Ups', 'Been So Long', 'Soorma', "Angela's Christmas", 'The Mars Generation', 'Kalushi : The Story of Solomon Mahlangu', 'The Maus', 'Family Blood', 'Pihu', 'Superlopez', 'Judd Apatow: The Return', 'Armed to the Teeth', 'Sarah Silverman: A Speck of Dust', 'Pa Paandi', 'Nobody Speak: Trials of the Free Press', 'Aapla Manus', 'Dismissal', 'Christmas Catch', 'F.R.E.D.I.', 'Love Beats Rhymes', 'Robozuna', 'Naam Shabana', 'Brian Regan: Nunchucks and Flamethrowers', '#realityhigh', 'We Speak Dance', 'DeRay Davis: How to Act Black', 'Def Comedy Jam 25', 'Take My Brother Away', 'Paranormal Investigation', 'LEGO Elves: Secrets of Elvendale', 'Motown Magic', 'The Suit', 'Dave Chappelle: Equanimity & The Bird Revelation', 'Amy Schumer: The Leather Special', 'Samantha!', 'Bon Cop Bad Cop 2', 'A Very Country Christmas', 'Paprika', 'Close Enemies', 'A Fortunate Man', 'Pup Star: Better 2Gether', 'The 3rd Eye', "Barbra: The Music ... The Mem'ries ... The Magic!", 'Age of Rebellion', 'Unbridled', 'Sabrina', 'Maz Jobrani: Immigrant', '48 Christmas Wishes', 'Falling in Love Like a Romantic Drama', 'Nailed It! Holiday!', 'How to Get Over a Breakup', 'Pachamama', 'Katherine Ryan: In Trouble', '#ABtalks', 'Part-Time Idol', 'Standup and Away! with Brian Regan', 'Ascharya Fuck It', 'Super Monsters', 'Dear Son', 'Sofía Niño de Rivera: Natural Selection', 'Nappily Ever After', 'Judwaa 2', 'Christina P: Mother Inferior', 'Ari Shaffir: Double Negative', 'Forgive Us Our Debts', 'Milada', 'Lost Song', 'Check The Store Next Door', 'First and Last', 'Buddy Thunderstruck', 'Oh My Ghost', 'Right Here Right Now', 'Monkart', 'The Many Faces of Ito', 'ID-0', 'Mustang Island', 'Cycle', 'Westside', 'Paradox', 'Sparring', 'The Chase', 'Age of Tanks', 'Invisible', 'Regiment Diaries', 'Tiffany Haddish: She Ready! From the Hood to Hollywood!', 'Party Monster: Scratching the Surface', 'Goyo: The Boy General', '5 Star Christmas', 'Ani... Dr. Kashinath Ghanekar', 'Suzzanna: Buried Alive', 'Stree', 'A Champion Heart', 'Burning Sands', 'Judah Friedlander: America Is the Greatest Country in the United States', 'Take the 10', 'Aurora', 'The Bros', 'Jim Norton: Mouthful of Shame', 'Merku Thodarchi Malai', 'Clair Obscur', 'Ponysitters Club', 'Blanche Gardin: I Talk to Myself', 'Being Napoleon', 'The Milk System', 'The Price of Success', 'Kuntilanak', 'Dhh', 'REA(L)OVE', 'Malena Pichot: Estupidez compleja', 'The Girl Allergic to Wi-Fi', 'Mauli', 'On Children', 'Samouni Road', 'Chief Daddy', 'CIA: Comrade In America', 'The Sound of Your Heart: Reboot', 'Bayonet', 'In the Family', 'Bert Kreischer: Secret Time', 'Gad Gone Wild', 'Counterpunch', 'El Potro: lo mejor del amor', 'Rajma Chawal', 'Cupcake & Dino - General Services', 'Russell Howard: Recalibrate', 'Deranged', 'Marlon Wayans: Woke-ish', 'Monster Island', 'Best.Worst.Weekend.Ever.', 'Liberated: The New Sexual Revolution', 'Your Son', 'Kingdom of Us', 'Prince of Peoria', 'Njan Prakashan', 'Target', 'Maria Bamford: Old Baby', 'Gad Elmaleh: American Dream', 'Rodney King', 'Made in Mexico', 'Alter Ego', 'Te Ata', 'The Last Hour', 'Loudon Wainwright III: Surviving Twin', "Michael Bolton's Big, Sexy Valentine's Day Special", 'A Sort of Family', 'In Line', 'All the Reasons to Forget', 'Buddy Thunderstruck: The Maybe Pile', 'Laerte-se', "Chicken Soup for the Soul's Being Dad", 'Awe!', 'Notes from Dunblane: Lessons from a School Shooting', 'ReMastered: Who Shot the Sheriff', 'Period. End of Sentence.', 'Good Game: The Beginning', 'Tattoo of Revenge', 'Love Jacked', 'Animas', 'The Bridge', 'The Last Runaway', 'Turkish Dance School', 'Bigger Than Africa', 'Lionheart', 'Russell Brand: Re:Birth', 'El club de los buenos infieles', 'Jeff Dunham: Relative Disaster', 'The Most Assassinated Woman in the World', 'Semesta', 'Stars in the Sky: A Hunting Story', 'Cook Off', "Kevin James: Never Don't Give Up", 'Heaven Without People', 'My Birthday Song', 'Taramani', 'Love.com', 'Born Racer', 'Aggretsuko: We Wish You A Metal Christmas', 'Manu', 'Exes Baggage', 'Teefa in Trouble', 'Up Among the Stars', 'Food on the Go', 'Nigerian Prince', 'Bangkok Love Stories 2: Innocence', 'Treehouse Detectives', 'Isoken', 'God Calling', 'The Judgement', 'The Lost Brother', 'Weapon of Choice', 'Lucas Brothers: On Drugs', 'A StoryBots Christmas', 'YG Future Strategy Office', 'The Birth Reborn 2', 'The Doll 2', 'Free Rein: The Twelve Neighs of Christmas', 'Fishtronaut: The Movie', 'Freej Al Taibeen', 'The Trader', 'For Here or to Go?', "Ayotzinapa: The Turtle's Pace", 'Rodney Carrington: Here Comes the Truth', 'Coffee for All', 'No One Will Ever Know', 'Fanatyk', 'Listen', "Can't Help Falling in Love", 'Genius', 'Motu Patlu Kung Fu Kings 4 The Challenge of Kung Fu Brothers', 'Marc Maron: Too Real', 'Mission Kathmandu: The Adventures of Nel